### PR TITLE
Contact us database and appattack database with auto email feature

### PR DESCRIPTION
**Pull request by s223541137**

### CODE REVIEW

**Review by s-bonnor — CHANGES_REQUESTED** [review]
Trying to submit the form throws an error
image
The styling on the appattack/join/ page is also messed up
image

**Review by s-bonnor — CHANGES_REQUESTED** [review]
Looks good
just need you to fix the merge conflicts now

**Comment by s223541137** [comment]
Fixed the merge conflict.

**Review by s-bonnor — APPROVED** [review]
Looks good

**Pull request merged**
