### PR TITLE
resolved issue on main header page of button hover and layout display

### PR DESCRIPTION
**Pull request by NaeemTufail0**

### CODE REVIEW

**Comment by s-bonnor** [comment]
could you elaborate on what issue this fixes? possibly with screenshots

**Comment by NaeemTufail0** [comment]
> could you elaborate on what issue this fixes? possibly with screenshots

/hi Sam, I have fixed the issue on home screen in Explore Projects Button as there was overlay issue and we were unable to see full button, and Join us button was not clickable in all sections of button so I fixed that one also. I am sharing a short loom video link explaining the problem. https://www.loom.com/share/3449ea53ce0f40aab486f0cf48ac5234?sid=2eca88ca-b129-4414-8f6f-723066e0866d

**Review by s-bonnor — APPROVED** [review]
Looks good, will be merged in a little bit

**Review by s-bonnor — CHANGES_REQUESTED** [review]
Sorry, noticed an issue with this, it prevents actually clicking any of the sign-in or sign-up links

**Comment by NaeemTufail0** [comment]
> Sorry, noticed an issue with this, it prevents actually clicking any of the sign-in or sign-up links

Check now.

**Review by s-bonnor — APPROVED** [review]
Looks good now

**Pull request merged**
